var fs = require('fs-extra'),
    path = require('path'),
    du = require('du'),
    globby = require('globby'),
    Q = require('q'),
    targets = require('./targets'),
    cli = require('./cli');


function parseIgnoreFile(ignoreFile) {
    return Q

        .nfcall(fs.ensureFile, ignoreFile.path)

        .then(function () {
            return Q.nfcall(fs.readFile, ignoreFile.path);
        })

        .then(function (content) {
            //NOTE: yep, so selfish...
            ignoreFile.content = content.toString() ||
                                 '# Generated by dmn (https://github.com/inikulin/dmn)';

            ignoreFile.patterns = ignoreFile.content
                .replace(/\r\n?/g, '\n')
                .split('\n')
                .map(function (str) {
                    return str.trim();
                })
                .filter(function (str) {
                    //NOTE: remove empty strings and comments
                    return str && str.indexOf('#') !== 0;
                });
        });
}

function findPatternsToAdd(projectDir, ignoreFile) {
    var patternsToAdd = [];

    var globPromises = targets.map(function (pattern) {
        return Q

            .nfcall(globby, pattern, {cwd: projectDir})

            .then(function (files) {
                if (files.length)
                    patternsToAdd.push(pattern);
            });
    });

    return Q

        .all(globPromises)

        .then(function () {
            //NOTE: skip already ignored patterns and patterns which should not be ignored
            patternsToAdd = patternsToAdd.filter(function (pattern) {
                return ignoreFile.patterns.indexOf(pattern) === -1 &&
                       ignoreFile.patterns.indexOf('!' + pattern) === -1;
            });

            return patternsToAdd;
        });
}

function savePatterns(ignoreFile, patternsToAdd) {
    ignoreFile.content += '\r\n\r\n' + patternsToAdd.join('\r\n');

    return Q

        .nfcall(fs.writeFile, ignoreFile.path, ignoreFile.content)

        .then(function () {
            cli.ok('.npmignore file was updated.');

            return 'OK: saved';
        });
}

function confirmSave(ignoreFile, patternsToAdd) {
    return Q

        .Promise(function (done) {
            cli.confirm('Save?', done);
        })

        .then(function (yes) {
            if (yes)
                return savePatterns(ignoreFile, patternsToAdd);

            cli.ok('.npmignore file update was canceled.');

            return 'OK: canceled';
        });
}

//API
module.exports = function (projectDir, options) {
    var ignoreFile = {
        path: path.join(projectDir, './.npmignore'),
        content: '',
        patterns: []
    };

    cli.info('Analyzing project...').spin();

    return parseIgnoreFile(ignoreFile)

        .then(function () {
            return findPatternsToAdd(projectDir, ignoreFile);
        })

        .then(function (patternsToAdd) {
            if (!patternsToAdd.length) {
                cli.ok('Unignored patterns was not found. Your .npmignore file is already perfect.');

                return 'OK: already-perfect';
            }

            cli.info('Following patterns will be added to .npmignore file:');
            cli.list(patternsToAdd);

            if (options.force)
                return savePatterns(ignoreFile, patternsToAdd);

            return confirmSave(ignoreFile, patternsToAdd);
        });
};

